In [ ]:
#Load the csv file.
import numpy as np 
import pandas as pd 

df = pd.read_csv('/content/weatherAUS.csv')
print('Size of weather data frame is :',df.shape)
df[0:5]

Size of weather data frame is : (73987, 24)


Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0           W           44.0          W  ...        22.0       1007.7   
1         WNW           44.0        NNW  ...        25.0       1010.6   
2         WSW           46.0          W  ...        30.0       1007.6   
3          NE           24.0         SE  ...        16.0       1017.6   
4           W           41.0        ENE  ...        33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1007.1       8.0       NaN     16.9     21.8         No      0.0   
1       1007.8       NaN       NaN     17.2     24.3         No      0.0   
2       1008.7       NaN       2.0     21.0     23.2         No      0.0   
3       1012.8       NaN       NaN     18.1     26.5         No      1.0   
4       1006.0       7.0       8.0     17.8     29.7         No      0.2   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 24 columns]

In [ ]:
#columns have maximum null values
df.count().sort_values()

Sunshine         29770
Evaporation      36308
Cloud3pm         44460
Cloud9am         45418
Pressure9am      64289
Pressure3pm      64340
WindDir9am       67423
WindGustDir      68484
WindGustSpeed    68491
WindDir3pm       71470
WindSpeed3pm     72265
Humidity3pm      72464
Temp3pm          72740
WindSpeed9am     72871
Humidity9am      72887
RainToday        73083
Rainfall         73084
Temp9am          73215
MinTemp          73550
MaxTemp          73774
RainTomorrow     73986
RISK_MM          73986
Location         73987
Date             73987
dtype: int64

In [ ]:
#dropping four columns,location column, date column too.RISK_M
df = df.drop(columns=['Sunshine','Evaporation','Cloud3pm','Cloud9am','Location','RISK_MM','Date'],axis=1)
df.shape

(73987, 17)

In [ ]:
#dropping all null values in df
df = df.dropna(how='any')
df.shape

(57413, 17)

In [ ]:
#Z-score to detect and remove the outliers.
from scipy import stats
z = np.abs(stats.zscore(df._get_numeric_data()))
print(z)
df= df[(z < 3).all(axis=1)]
print(df.shape)

[[0.29208099 0.03858488 0.21204191 ... 1.24416256 0.12016625 0.09900656]
 [0.71697985 0.36994436 0.28570824 ... 1.14318119 0.17256558 0.48672086]
 [0.20799258 0.46031513 0.28570824 ... 1.013348   0.83629039 0.31612657]
 ...
 [0.31335552 1.19648228 1.50683906 ... 0.73218711 0.70075654 1.3587992 ]
 [0.58243841 1.1512969  0.37728871 ... 0.50137255 1.03261894 1.01761062]
 [1.13742187 1.4224092  0.2545115  ... 1.02070531 1.43434711 1.40532492]]
(54574, 17)


In [ ]:
#changing yes or no to 1 or 0 for RainToday and RainTomorrow
df['RainToday'].replace({'No': 0, 'Yes': 1},inplace = True)
df['RainTomorrow'].replace({'No': 0, 'Yes': 1},inplace = True)

categorical_columns = ['WindGustDir', 'WindDir3pm', 'WindDir9am']
for col in categorical_columns:
    print(np.unique(df[col]))
# transform the categorical columns
df = pd.get_dummies(df, columns=categorical_columns)
df.iloc[4:9]

['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']


MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
4     17.5     32.3       1.0           41.0           7.0          20.0   
5     14.6     29.7       0.2           56.0          19.0          24.0   
6     14.3     25.0       0.0           50.0          20.0          24.0   
7      7.7     26.7       0.0           35.0           6.0          17.0   
8      9.7     31.9       0.0           80.0           7.0          28.0   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir9am_NNW  \
4         82.0         33.0       1010.8       1006.0  ...               0   
5         55.0         23.0       1009.2       1005.4  ...               0   
6         49.0         19.0       1009.6       1008.2  ...               0   
7         48.0         19.0       1013.4       1010.1  ...               0   
8         42.0          9.0       1008.9       1003.6  ...               0   

   WindDir9am_NW  WindDir9am_S  WindDir9am_SE  WindDir9am_SSE  WindDir9am_SSW  \
4              0             0              0               0               0   
5              0             0              0               0               0   
6              0             0              0               0               0   
7              0             0              0               1               0   
8              0             0              1               0               0   

   WindDir9am_SW  WindDir9am_W  WindDir9am_WNW  WindDir9am_WSW  
4              0             0               0               0  
5              0             1               0               0  
6              1             0               0               0  
7              0             0               0               0  
8              0             0               0               0  

[5 rows x 62 columns]

In [ ]:
#data preprocessing- using MinMaxScaler
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
scaler.fit(df)
df = pd.DataFrame(scaler.transform(df), index=df.index, columns=df.columns)
df.iloc[4:10]

MinTemp   MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
4  0.664789  0.734375  0.037594       0.459459      0.128205      0.409091   
5  0.583099  0.666667  0.007519       0.662162      0.435897      0.500000   
6  0.574648  0.544271  0.000000       0.581081      0.461538      0.500000   
7  0.388732  0.588542  0.000000       0.378378      0.102564      0.340909   
8  0.445070  0.723958  0.000000       0.986486      0.128205      0.590909   
9  0.540845  0.677083  0.052632       0.283784      0.333333      0.204545   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir9am_NNW  \
4     0.783133     0.323232     0.329384     0.265700  ...             0.0   
5     0.457831     0.222222     0.291469     0.251208  ...             0.0   
6     0.385542     0.181818     0.300948     0.318841  ...             0.0   
7     0.373494     0.181818     0.390995     0.364734  ...             0.0   
8     0.301205     0.080808     0.284360     0.207729  ...             0.0   
9     0.493976     0.262626     0.239336     0.258454  ...             0.0   

   WindDir9am_NW  WindDir9am_S  WindDir9am_SE  WindDir9am_SSE  WindDir9am_SSW  \
4            0.0           0.0            0.0             0.0             0.0   
5            0.0           0.0            0.0             0.0             0.0   
6            0.0           0.0            0.0             0.0             0.0   
7            0.0           0.0            0.0             1.0             0.0   
8            0.0           0.0            1.0             0.0             0.0   
9            0.0           1.0            0.0             0.0             0.0   

   WindDir9am_SW  WindDir9am_W  WindDir9am_WNW  WindDir9am_WSW  
4            0.0           0.0             0.0             0.0  
5            0.0           1.0             0.0             0.0  
6            1.0           0.0             0.0             0.0  
7            0.0           0.0             0.0             0.0  
8            0.0           0.0             0.0             0.0  
9            0.0           0.0             0.0             0.0  

[6 rows x 62 columns]

In [ ]:
#important features for RainTomorrow
#Using SelectKBest to get the top features
from sklearn.feature_selection import SelectKBest, chi2
X = df.loc[:,df.columns!='RainTomorrow']
y = df[['RainTomorrow']]
selector = SelectKBest(chi2, k=10)
selector.fit(X, y)
X_new = selector.transform(X)
print(X.columns[selector.get_support(indices=True)])

Index(['Rainfall', 'WindGustSpeed', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Temp3pm', 'RainToday', 'WindDir3pm_N',
       'WindDir9am_N'],
      dtype='object')


In [ ]:

df = df[['Humidity3pm','Rainfall','RainToday','RainTomorrow','Temp3pm','Pressure9am']]
X = df[['Humidity3pm','Pressure9am','Temp3pm']] 
y = df[['RainTomorrow']]
print(y)

       RainTomorrow
0               0.0
1               0.0
2               0.0
3               0.0
4               0.0
...             ...
73981           1.0
73982           1.0
73983           1.0
73984           1.0
73985           0.0

[54574 rows x 1 columns]


In [ ]:
#Logistic Regression 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_logreg = LogisticRegression(random_state=0)
clf_logreg.fit(X_train,y_train)
y_pred = clf_logreg.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy for Logistic Regression :',score)
print('Time taken for Logistic Regression :' , time.time()-t0)

Accuracy for Logistic Regression : 0.8418352389328643
Time taken for Logistic Regression : 0.14184260368347168


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
#Random Forest Classifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_rf = RandomForestClassifier(n_estimators=100, max_depth=4,random_state=0)
clf_rf.fit(X_train,y_train)
y_pred = clf_rf.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy for Random Forest :',score)
print('Time taken for Random Forest:' , time.time()-t0)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


Accuracy for Random Forest : 0.8369979478158898
Time taken for Random Forest: 1.6274681091308594


In [ ]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train,y_train)
y_pred = clf_dt.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy for Decision Tree :',score)
print('Time taken for Decision Tree:' , time.time()-t0)

Accuracy for Decision Tree : 0.7653180885370859
Time taken for Decision Tree: 0.1456286907196045


In [ ]:
#Support Vector Machine
from sklearn import svm
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_svc = svm.SVC(kernel='linear')
clf_svc.fit(X_train,y_train)
y_pred = clf_svc.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy for Support Vector Machine :',score)
print('Time taken for Support Vector Machine:' , time.time()-t0)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy for Support Vector Machine : 0.8394333815404013
Time taken for Support Vector Machine: 94.38973832130432


In [ ]:
from sklearn.ensemble import RandomForestClassifier
df1 = pd.read_csv('/content/weather-df13c-default-rtdb-export (4) (1).csv')
print('Size of weather data frame is :',df1.shape)
df1=df1.rename(columns={"HUMIDITY":"Humidity3pm","PRESSURE":"Pressure9am","TEMP":"Temp3pm"})
clf_rf = RandomForestClassifier(n_estimators=100, max_depth=4,random_state=0)
clf_rf.fit(X,y)
y_pred = clf_rf.predict(df1)
qw=list(y_pred)
print(qw)
if round(qw[0])==0:
  print("Rain will not fall")
else:
  print("Rain will fall")


Size of weather data frame is : (1, 3)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


[0.0]
Rain will not fall


In [ ]:
#Logistic Regression 
from sklearn.linear_model import LogisticRegression
clf_logreg1 = LogisticRegression(random_state=0)
clf_logreg1.fit(X,y)
y_pred1 = clf_logreg1.predict(df1)
qw1=list(y_pred1)
print(qw1)
if round(qw1[0])==0:
  print("Rain will not fall")
else:
  print("Rain will fall today")



/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.0]
Rain will not fall


In [ ]:
'''
#y_pred=list(y_pred)
y_test=list(y_test['RainTomorrow'])
print(y_test)
l=[]
for i in range(len(y_pred)):
  if y_test[i]==y_pred[i]:
    l.append("yes")
  else:
    l.append("No")
print(len(y_pred))
print(l.count("yes"))
'''